PCS/urls.py
import os
from django.conf.urls import patterns, include, url
from PCS import views, settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'PCS.views.home', name='home'),
    # url(r'^PCS/', include('PCS.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.banned, name='banned'),
    url(r'^secret/$', views.index, name='home'),
    url(r'^seats_check/', include('seats_check.urls')),
    url(r'^accounts/', include('user_mode.urls')),
    url(r'^weixin/', include('weixin.urls')),
    url(r'^not_completed$', views.not_completed, name='not_completed'),
    url(r'^api/$', views.api, name='api'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^used_book/', include('used_book.urls')),
)

used_book/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('used_book.views',
    # Examples:
    # url(r'^$', 'PCS.views.home', name='home'),
    # url(r'^PCS/', include('PCS.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', 'view',
        name = 'used_book_view'),
    url(r'^post/$', 'post',
        name = 'used_book_post'),
)

used_book/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    name = models.CharField(max_length=20)
    publisher = models.CharField(max_length=20)
    course = models.CharField(max_length=20)
    price = models.FloatField()
    seller_id = models.CharField(max_length=20)
    seller_contact = models.CharField(max_length=20)

user_mode/models.py
from django.db import models
from django.contrib.auth.models import User as Auth_User
from seats_check.models import Section
from seats_check.util import ParserException
# Create your models here.


class MyUserManager(models.Manager):
    def create_user(
        self,
        username,
        email,
        password,
        firstname,
        lastname,
    ):
        user = Auth_User.objects.create_user(
            username,
            email,
            password,
            first_name=firstname,
            last_name=lastname,
        )
        my_user = self.create(
            user=user,
            pwd=password,
        )
        return my_user


class MyUser(models.Model):
    user = models.OneToOneField(Auth_User, primary_key=True)
    pwd = models.CharField(max_length=100)
    sections = models.ManyToManyField(Section)

    def add_section(self, crn, term, send_restrict=False):
        if self.sections.count() < 5:
            sec = None
            try:
                sec = Section.objects.get(crn=crn, term=term)
            except:
                sec = Section.objects.create_new_section(crn, term)
            if not isinstance(sec, Exception):
                if not sec in self.sections.all():
                    self.sections.add(sec)
                    if send_restrict:
                        sec.add_restrict_user(self)
                    return sec
            else:
                raise sec
            return None
        else:
            raise ParserException('You cannot subscribe more than 5 sections')

    def add_sections(self, **secs):
        result = []
        for crn, term in secs.iteritems():
            sec = None
            try:
                sec = Section.objects.get(crn, term)
            except:
                sec = Section.objects.create_new_section(crn, term)
            if not isinstance(sec, Exception):
                if not sec in self.sections.all():
                    self.sections.add(sec)
                    result.append(sec)
            else:
                err = sec
                raise err
        return result

    objects = MyUserManager()

class Invitation(models.Model):
    code = models.CharField(max_length=20)
    used = models.BooleanField(default=False)

    def add_invitation(self,code):
        Invitation.objects.create(code=code)

used_book/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from used_book.models import Book

# Create your views here.
def view(request):
    context = {}
    if request.method == 'GET':
        books = Book.objects.all()
        context = {'books':books}
        return render(request, 'used_book_view.html', context)
    elif request.method == 'POST':
        pk = request.POST.get('pk')
        try:
            book = Book.objects.get(pk=pk)
            book.delete()
            books = Book.objects.all()
            context = {'books':books}
        except Exception as e:
            context = {'error':e}
        return render(request, 'used_book_view.html', context)


def post(request):
    if request.method == 'GET':
        return render(request,'used_book_post.html', {'error':''})
    elif request.method == 'POST':
        param = request.POST
        name = param.get('name')
        publisher = param.get('publisher')
        course = param.get('course')
        price = param.get('price')
        seller_id = param.get('seller_id')
        seller_contact = param.get('seller_contact')
        try:
            Book.objects.create(
                name=name,
                publisher=publisher,
                course=course,
                price=price,
                seller_id=seller_id,
                seller_contact=seller_contact,
            )
        except Exception as e:
            context = {'error':e}
            return render(request,'used_book_post.html', context)
        return redirect('used_book_view')

templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/contact.css" %}" rel="stylesheet">
{% endblock %}

{% block active_contact %}class="active"{% endblock %}

{% block content %}
<div class="unit">
    <legend><h1 class="pull-center">
            API
    </h1></legend>
    <div class="row-fliud">
        <div class="span6 info-bloc">
            <p>RenRen Account</p>
        </div>
    </div>
</div>
{% endblock %}

templates/api.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/api.css" %}" rel="stylesheet">
{% endblock %}

{% block active_api %}class="active"{% endblock %}

{% block content %}
<div class="unit">
    <legend><h1 class="pull-center">
            API
    </h1></legend>

    <div>
        <div class="alert alert-info">URL: http://purdue-class.chenrendong.com/seats_check/crns/</div>
        <ul>
            <li>
                <div class="info"><b>POST</b> to API URL with following format:</div>
                <ul>
                    <li>
                        <div class="info">{term:term,content:[*crns]}</div>
                    </li>
                    <li>
                    <div class="info">Example: {"term":"201410","content":["10001","10002"]}</div>
                    </li>
                </ul>
            </li>
            <li>
                <div class="info">Server returns a list of results</div>
            </li>
            <li>
                <div class="info">The result of a single class is always a **JSON** containing {code : 0/1 , content : String or Tuple}</div>
                <ul>
                    <li>
                        <div class="info">code is the flag, 0 represents as failed, 1 represnts as successful</div>
                    </li>
                    <li>
                        <div class="info">If code is 0, then content is a string containing the error message</div>
                    </li>
                    <li>
                        <div class="info">If code is 1, then centent is a tuple containing all the class information</div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

templates/banned.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/home.css" %}" rel="stylesheet">
{% endblock %}

{% block active_home %}class="active"{% endblock %}

{% block nav %}
{% endblock %}

{% block content %}
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
          <h1 class="welcome">Purdue Course Seats has been banned</h1>
      </div>
  <hr>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!-- saved from url=(0053)http://twitter.github.io/bootstrap/examples/hero.html -->
<html lang="en"><head _wxhkphogpkobbkjccgfifhfjlahnoocnan_="shake_1.0"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Purdue Course Seats</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"></link>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    {% block js %}
    {% endblock %}
    {% block css %}
    {% endblock %}
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="http://twitter.github.io/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="http://twitter.github.io/bootstrap/assets/ico/favicon.png">
  </head>

  <body>

      {% block nav %}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'home' %}">PCS</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li {% block active_home%}{% endblock %}><a href="{% url 'home' %}">Home</a></li>
                <li {% block active_dashboard%}{% endblock %}><a href="{% url 'user_mode_dashboard' %}">Dashboard</a></li>
              <li {% block active_api%}{% endblock %}><a href="{% url 'api' %}">API</a></li>
              <!--
              <li class="dropdown">
                <a href= "#" class="dropdown-toggle" data-toggle="dropdown">MultiPlatform<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'not_completed' %}">WeChat</a></li>
                  <li><a href="{% url 'not_completed' %}">Mobile</a></li>
                  <li><a href="{% url 'not_completed' %}">Download</a></li>
                </ul>
              </li>
              <li {% block active_about%}{% endblock %}><a href="{% url 'not_completed' %}">About</a></li>
              -->
              <li {% block active_contact%}{% endblock %}><a href="{% url 'contact' %}">Contact</a></li>
            </ul>

            {% if not request.user.is_authenticated %}
                <form action="{% url 'user_mode_login' %}" method="POST" class="navbar-form pull-right">
                {% csrf_token %}
                  <input class="span2" name="username" type="text" placeholder="Username">
                  <input class="span2" name="password" type="password" placeholder="Password">
                  <button type="submit" class="btn">Sign in</button>
                </form>
            {% else %}
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a href= "#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{ request.user.get_full_name }}<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'user_mode_profile' %}">Profile</a></li>
                        <li><a href="{% url 'user_mode_logout' %}">Log Out</a></li>
                    </ul>
                </li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    {% endblock %}

    <div class="container">
    {% block content %}
    {% endblock %}
      <footer>
        <p>© Rendong Chen 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new
            Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-42540540-1', 'chenrendong.com');
        ga('send', 'pageview');

    </script>
  </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/contact.css" %}" rel="stylesheet">
{% endblock %}

{% block active_contact %}class="active"{% endblock %}

{% block content %}
<div class="unit">
    <legend><h1 class="pull-center">
            Contact Information
    </h1></legend>
    <div class="row-fluid">
        <div class="span6 info-bloc">
            <h3 class="info-label">RenRen Account:</h3>
            <h3 class="info-label">Weibo Account:</h3>
            <h3 class="info-label">WeChat Account:</h3>
            <h3 class="info-label">Email Address:</h3>
            <h3 class="info-label">QQ:</h3>
        </div>
        <div class="span6 info-bloc">
            <h3 class="info-label"><a href="http://www.renren.com/247605993">Rendong Chen</a></h3>
            <h3 class="info-label"><a href="http://weibo.com/u/2234534512">RyanCccc</a></h3>
            <h3 class="info-label">BoilerUp_PCS</h3>
            <h3 class="info-label"><a href="mailto:chenrd769@gmail.com">chenrd769@gmail.com</a></h3>
            <h3 class="info-label"><a href="http://wpa.qq.com/msgrd?V=0&amp;Uin=799080508&amp;Site=http://purdue-class.chenrendong.com/contact/&amp;Menu=yes" target="_blank">799080508</a></h3>
        </div>
    </div>
</div>
{% endblock %}

templates/crn_search.html
{% extends "dashboard_base.html" %}
{% load staticfiles %}

{% block active_search %}active{% endblock %}

{% block tab_title %}CRN Search{% endblock %}

{% block main_table %}
<legend class="pull-center">
    <h3>
        {{ classes.0.code }}
    </h3>
    <h3>
        {{ classes.0.name }}
    </h3>
</legend>
<table class="table table-hover">
    <tr>
        <th>Section Number</th>
        <th>Section CRN</th>
        <th>Section Time</th>
        <th>Section Type</th>
    </tr>
    {% for cl in classes %}
    <tr>
        <td>{{ cl.number }}</td>
        <td>{{ cl.crn }}</td>
        <td>{{ cl.class_time }}</td>
        <td>{{ cl.class_type }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

{% block search_label %}Class{% endblock %}
{% block search_name %}classname{% endblock %}

{% block submit_label %}Search{% endblock %}
{% block form %}
<form id="add_sec" class="form-inline add-btn" name="addsec" action="." method="POST">{% csrf_token %}
    <div>{{ error }}</div>
    <label>Class:</label><input class="input-small" type="text" name="classname" placeholder="eg. CS180">
    <label>Term: </label><input class="input-small" type="text" name="term" value="sp14">
    <input class="btn" type="submit" value="Search">
</form>
{% endblock %}

templates/dashboard.html
{% extends "dashboard_base.html" %}
{% load staticfiles %}

{% block js_addition %}
    <script type="text/javascript" src="{% static "js/subscribe.js" %}"></script>
{% endblock %}

{% block active_sub %}active{% endblock %}
{% block tab_title %}Subscribed Sections{% endblock %}
{% block main_table %}
<table class="table table-hover">
    <tr>
        <th>CRN</th>
        <th>Class Name</th>
        <th>Max Seats</th>
        <th>Actived Seats</th>
        <th>Remain Seats</th>
        <th>Class Term</th>
        <th>Class Code</th>
        <th>Section Number</th>
        <th>Popularity</th>
        <th>Remove</th>
    </tr>
    {% for sec in sections %}
    <tr>
        <td>{{ sec.crn }}</td>
        <td>{{ sec.name }}</td>
        <td>{{ sec.max_seats_num }}</td>
        <td>{{ sec.current_seats_num }}</td>
        <td class="important">{{ sec.remain_seats_num }}</td>
        <td>{{ sec.get_term }}</td>
        <td>{{ sec.code }}</td>
        <td>{{ sec.number }}</td>
        <td>{{ sec.myuser_set.count }}</td>
        <td>
            <form id="remove_crn" action="{% url 'user_mode_remove_crn' %}" method="POST" style="margin:0">
                {% csrf_token %}
                <input type="hidden" name="crn" value="{{ sec.crn }}">
                <input type="hidden" name="term" value="{{ sec.term }}">
                <input class="btn" type="submit" value="Remove">
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}
{% block form %}
<form id="add-sec" class="form-inline add-btn" name="addsec" action="." method="POST">{% csrf_token %}
    {% if error %}
        <div class="alert alert-error">{{ error }}</div>
    {% endif %}
    <div>
        <label>Add CRN:</label><input id="crn-input" class="input-small" type="text" name="crn" placeholder="Section CRN">
        <label>Term(Any format): </label><input id="term-input" class="input-small" type="text" name="term" value="sp14">
    </div>
    <div class="checkbox">
        <label>
            <input class="send-restrict-checkbox" type="checkbox" name="send_restrict" value="restrict">Send notifictions only when seats changed from empty.
        </label>
    </div>
    <div>
        <button id="quick-search-btn" class="btn" type="button" href="#quick-search-modal" data-toggle="modal">Quick Search</button>
        <input id="subscribe-btn" class="btn" type="submit" value="Subscribe Section">
    </div>
</form>

<div id="quick-search-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Result</h3>
    </div>
    <div class="modal-body">
        <div class="result-error alert-error"></div>
        <div class="form-horizontal result">
            <div class="control-group">
                <label class="control-label" for="inputName">Class Name</label>
                <div class="controls">
                    <label id="inputName" class="control-label static-data"></label>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputCode">Class Code</label>
                <div class="controls">
                    <label id="inputCode" class="control-label static-data"></label>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputNum">Section Number</label>
                <div class="controls">
                    <label id="inputNum" class="control-label static-data"></label>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputMax">Maximun Seats</label>
                <div class="controls">
                    <label id="inputMax" class="control-label static-data"></label>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputCur">Active Seats</label>
                <div class="controls">
                    <label id="inputCur" class="control-label static-data"></label>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputRem">Remain Seats</label>
                <div class="controls">
                    <label id="inputRem" class="control-label static-data"></label>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div class="checkbox pull-left">
            <label>
                <input class="send-restrict-checkbox" type="checkbox" name="send_restrict" value="restrict">Send notifictions only when seats changed from empty.
            </label>
        </div>
        <div class="pull-right">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
            <button id="save" class="btn btn-primary ">Subscribe it</button>
        </div>
    </div>
</div>
{% endblock %}

{% block alert %}
<div class="alert alert-info">Once there are seats released, server will send a notify email to <b>{{ request.user.email }}</b> instantly!</div> 
{% endblock %}

templates/dashboard_base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static "js/dashboard.js" %}"></script>
    {% block js_addition %}
    {% endblock %}
{% endblock %}

{% block active_dashboard %}class="active"{% endblock %}

{% block content %}
<div class="unit">
    <div class="navbar inner-navbar">
        <div class="navbar-inner">
            <a class="brand" href="{% url 'user_mode_dashboard' %}">Dashboard</a>
            <ul class="nav">
                <li class="{% block active_sub %}{% endblock %}"><a href="{% url 'user_mode_dashboard' %}">Subscribe Sections</a></li>
                <li class="{% block active_search %}{% endblock %}"><a href="{% url 'user_mode_crn_search' %}">CRN Search</a></li>
                <li class="{% block active_pro %}{% endblock %}"><a href="{% url 'user_mode_profile'%}">Profile</a></li>
            </ul>
        </div>
    </div>

    <legend><h1 class="pull-center">
            {% block tab_title %}{% endblock %}
    </h1></legend>
    {% block main_table %}
    {% endblock %}
    <br><br>
    {% block form %}
    {% endblock %}
    {% block alert %}
    {% endblock %}
</div>

<!--
<div class="if-btn-group">
<div id="scheduler-btn" for="scheduler" class="if-btn" src="http://timetable.mypurdue.purdue.edu/Timetabling/gwt.jsp?page=sectioning"><a class="btn btn-large iframe-btn">Purdue Scheduler</a></div>
<div id="mymail-btn" for="mymail" class="if-btn" src="http://mymail.purdue.edu"><a class="btn btn-large iframe-btn">MyMail System</a></div>
</div>
<!-- Modal -->
<iframe id="scheduler" class="iframe" src=""></iframe>
<iframe id="mymail" class="iframe" src=""></iframe>
-->
{% endblock %}

templates/index_bootstrap.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
    <link href="{% static "css/home.css" %}" rel="stylesheet">
{% endblock %}

{% block active_home %}class="active"{% endblock %}

{% block content %}
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
          <h1 class="welcome">Welcome to Purdue Course Seats!</h1>
          <div class="row-fluid">
              <div class="dec-pic span6">
                  <div id="myCarousel" class="carousel slide"> 
                      <ol class="carousel-indicators">      
                          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                          <li data-target="#myCarousel" data-slide-to="1"></li>
                          <li data-target="#myCarousel" data-slide-to="2"></li>
                      </ol>
                      <!-- Carousel items -->
                      <div class="carousel-inner">
                          <div class="active item">
                              <div id="demo1"></div>
                              <div class="carousel-caption">
                                  <h4>Web Application</h4>
                                  <p>You can subscribe your class in dashboard, once you subscribe classes, we will keep
                                  tracing the seats for you, and take care of it.</p>
                              </div>
                          </div>
                          <div class="item">
                              <div id="demo2"></div>
                              <div class="carousel-caption">
                                  <h4>Search CRN</h4>
                                  <p>Server can also check CRN for you, it's convenient to search your class's CRN</p>
                              </div>
                          </div>
                          <div class="item">
                              <div id="demo3"></div>
                              <div class="carousel-caption">
                                  <h4>Email Service</h4>
                                  <p>Server check your class seats every 20 seconds, once there is available seats, it
                                  will automatically send you an instant email to help you catch the class (Picture is
                                  just a demo)</p>
                              </div>
                          </div>
                          <div class="item">
                              <div id="demo4"></div>
                              <div class="carousel-caption">
                                  <h4>WeChat CRN check</h4>
                                  <p>WeChat Public Platform now can check CRNs, also, it supports to check course seats
                                  condition as well</p>
                              </div>
                          </div>
                      </div>
                      <!-- Carousel nav -->
                      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                  </div>
              </div>
              <div class="description span6">
                  <p>Parsers purdue class seats from Purdue Website</p>
                  <p>Keep tracking available class seats in real time</p>
                  <p>Update the latest seats in <b>every 5 minutes</b></p>
                  <p>Send email notification once new seats released</p>
                  {% if not request.user.is_authenticated %}
                  <p>
                    <a href="{% url 'user_mode_register' %}" class="btn btn-large">Register Now »</a>
                    <a href="{% url 'user_mode_login' %}" class="btn btn-inverse btn-large">Sign In »</a>
                  </p>
                  {% else %}
                    <p><a href="{% url 'user_mode_dashboard' %}" class="btn btn-inverse btn-large">My Dashboard »</a></p>
                  {% endif %}
                  <div class="alert alert-block" style="text-align:left">
                      <button type="button" class="close" data-dismiss="alert">&times;</button>
                      <h2>Notice!</h2>
                      <p>From 7/15, every user can only subscribe 5 sections.</p>
                      <p>The seats will be checked every 5 minutes due to the web traffic.</p>
                  </div>
              </div>
          </div>
      </div>

      <div class='row-fluid'>
          <div class="accordion-group banner span6">
              <div class="accordion-heading">
                  <div class="accordion-toggle" data-toggle="collapse" href="#autoregis-data">
                      <h3>
                          The most powerful feature:
                          <b>Auto Registration</b>
                      </h3>
                  </div>
              </div>
              <div id="autoregis-data" class="accordion-body collapse">
                  <div class="accordion-inner">
                      <h2>Auto Registration</h2>
                      <li>Communicate with MyPurdue System</li>
                      <li>Complete course registration automatically.</li>
                      <li>Register your desired courses at first time when new seats released</li>
                  </ul>
                  <p class="banner-btn"><a class="btn" href="{% url 'not_completed' %}">Coming Soon »</a></p>
                  </div>
              </div>
          </div>
          <div class="accordion-group banner span6">
              <div class="accordion-heading">
                  <div class="accordion-toggle" data-toggle="collapse" href="#api-data">
                      <h3>
                          The most convient tool:
                          <b>Seats Check API</b>
                      </h3>
                  </div>
              </div>
              <div id="api-data" class="accordion-body collapse">
                  <div class="accordion-inner">
                      <h2>Seats Check API</h2>
                      <li>URL: http://purdue-class.chenrendong.com/seats_check/</li>
                      <li>Support multiple CRNs check.</li>
                      <li>Return JSON format</li>
                      <li>Contain all the class information</li>
                  </ul>
                  <p class="banner-btn"><a class="btn" href="{% url 'api' %}">View details »</a></p>
                  </div>
              </div>
          </div>
      </div>
  <!-- Example row of columns -->
  <div class="row features">
      <div class="span4">
          <h2>Instant Email</h2>
          <ul>
              <li>Email you the latest seats available condition.</li>
              <li>Notify you when seats releasing instantly.</li>
          </ul>
          <p><a class="btn" href="{% url 'user_mode_profile' %}">Register my email now »</a></p>
      </div>
      <div class="span4">
          <h2>WeChat Public</h2>
          <ul>
              <li>Auto-reply the latest information</li>
              <li>Check all courses' CRN instantly</li>
          </ul>
          <p><a class="btn" href="{% url 'not_completed' %}">Coming Soon »</a></p>
      </div>
      <div class="span4">
          <h2>Mobile Applications</h2>
          <ul>
              <li>Multi-Platform including iOS, Android and Win8</li>
              <li>Communicate with server and update data.</li>
              <li>Get notification when new seats released</li>
          </ul>
          <p><a class="btn" href="{% url 'not_completed' %}">Coming Soon »</a></p>
      </div>
  </div>
  <hr>
{% endblock %}

templates/notcompleted.html
{% extends "base.html" %}

{% block content %}
<h1>Not completed yet</h1>
{% endblock %}